### ISSUE TITLE
浅谈 Unicorn 的多进程模型

### ISSUE THREAD

**Issue by nju520** [nju520/bobo-comments#2]
https://nju520.github.io/rack-unicorn 

 作为 Ruby 社区中老牌的 webserver，在今天也有很多开发者在生产环境使用 Unicorn 处理客户端的发出去的 HTTP 请求，与 WEBrick 和 Thin 不同，Unicorn 使用了完全不同的模型，提供了多进程模型批量处理来自客户端的请求。Unicorn 为 Rails 应用提供并发的方式是使用 fork 创建多个 worker 线程，监听同一个 Socket 上的输入。

**Comment by nju520** [comment]
雄关漫道真如铁, 而今迈步从头越

**Comment by nju520** [comment]
不错不错不错

**Comment by wenbohan** [comment]
不做白日梦

**Comment by wenbohan** [comment]
> @nju520
> 不错不错不错

得了吧

**Comment by nju520** [comment]
hehe

**Comment by nju520** [comment]
haha

**Comment by nju520** [comment]
wuwu

**Comment by nju520** [comment]
wtf

**Comment by nju520** [comment]
heng

**Comment by nju520** [comment]
ai

**Comment by nju520** [comment]
ya

**Comment by nju520** [comment]
走你

**Comment by nju520** [comment]
再来点

**Comment by nju520** [comment]
我还要

**Comment by nju520** [comment]
给你给你
