### ISSUE TITLE
2017 年总结 - 写在转职后的一个月

### ISSUE THREAD

**Issue by nju520** [nju520/bobo-comments#4]
https://nju520.github.io/2017-summary 

 一直以来都很少写这些比较软性的文章，一方面觉得没有太多可以写的事情，另一方面觉得写这种博客对读者来说没有太大的价值，不过作者在今天还是想对过去的 2017 年进行简单的总结，让自己更加清楚这一年有哪些的变化。在今年年初的时候曾经定下了两个非常简单的计划：看 30 本书、完成 20 篇博客；前者是一个输入的过程，后者是输出的过程，而这种可以量化的指标比较容易记录，对于完成与否也有一个确切的答案。

**Comment by wenbohan** [comment]
hehe
